name: 'Labeller action'
description: 'Automatically add  PR label based on branch prefix'
inputs:
  branch:
    description: 'Branch name'
    required: true
  token:
    description: 'Token'
    required: true
  repo:
    description: 'Repository name'
    required: true
  issue_number:
    description: 'Issue number'
    required: true
outputs:
  label:
    description: 'The label that was applied'
runs:
  using: 'node12'
  main: 'dist/index.js'
