name: "Labeller action"
description: "Automatically add PR label based on branch prefix"
inputs:
  token:
    description: "Github Token"
    required: true
  labels:
    description: "Comma separated list of labels to match"
    required: true
outputs:
  label:
    description: "The label that was applied"
runs:
  using: "node12"
  main: "dist/index.js"
