on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to set the PR label based on the branch name
    steps:
      - name: Action step
        uses: 'nbycomp/github-labeller-action@v1'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ github.event.number }}
          branch: ${{ github.event.pull_request.head.ref }}
          repo: ${{ github.event.pull_request.head.repo.name }}